
server:
  port: 8085
  servlet:
    context-path: /api/v1/
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tvcam?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect

  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  jackson:
    time-zone: Africa/Lagos
    date-format: dd-MM-yyyy HH:mm:ss

security:
  jwt:
    security-key: 7638792F423F4428472B4B6250655368566D597133743677397A244326462948404D635166546A576E5A7234753778214125442A472D4B6150645267556B5870
    expiration: 86400000 #1 day