
spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        globally_quoted_indentifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true

  sql:
    init:
      mode: never
      continue-on-error: false
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /**
  jackson:
    time-zone: Africa/Lagos
    date-format: dd-MM-yyyy HH:mm:ss

security:
  jwt:
    security-key: ${JWT_SECRET_KEY}
    expiration: ${JWT_EXPIRATION_TIME} #1 day


server:
  port: ${CONTAINER_PORT:8080}
  servlet:
    context-path: /api/v1/
  error:
    path: /user/error
    whitelabel:
      enabled: false